CATEGORIES = [
    "College",
    "Work",
    "Personal",
    "Documents",
    "Images",
    "Videos",
    "Music",
    "Archives",
]


EXTENSION_CATEGORIES = {
    "Images": {
        ".jpg",
        ".jpeg",
        ".png",
        ".gif",
        ".webp",
        ".bmp",
        ".svg",
        ".tiff",
    },
    "Videos": {
        ".mp4",
        ".mkv",
        ".avi",
        ".mov",
        ".wmv",
        ".webm",
        ".flv",
    },
    "Music": {
        ".mp3",
        ".wav",
        ".flac",
        ".aac",
        ".ogg",
        ".m4a",
    },
    "Archives": {
        ".zip",
        ".rar",
        ".7z",
        ".tar",
        ".gz",
        ".bz2",
    },
    "Documents": {
        ".pdf",
        ".doc",
        ".docx",
        ".txt",
        ".rtf",
        ".odt",
        ".xls",
        ".xlsx",
        ".csv",
        ".ppt",
        ".pptx",
    },
}


KEYWORD_CATEGORIES = {
    "College": {
        "assignment",
        "exam",
        "semester",
        "lecture",
        "lab",
        "practical",
        "dbms",
        "java",
        "python",
        "os",
        "operating-system",
        "cn",
        "dsa",
        "data-structure",
        "college",
        "university",
        "course",
        "subject",
    },
    "Work": {
        "invoice",
        "meeting",
        "client",
        "project",
        "report",
        "proposal",
        "presentation",
        "salary",
        "office",
        "work",
        "business",
        "company",
        "employee",
    },
    "Personal": {
        "personal",
        "family",
        "travel",
        "vacation",
        "passport",
        "insurance",
        "medical",
        "home",
        "private",
    },
}


CONTEXT_CATEGORIES = {
    "College": {
        "college",
        "university",
        "campus",
        "semester",
        "assignments",
        "assignment",
        "lectures",
        "lecture",
        "labs",
        "lab",
        "subjects",
        "subject",
        "course",
        "dbms",
        "java",
        "python",
        "dsa",
    },
    "Work": {
        "work",
        "office",
        "company",
        "business",
        "projects",
        "project",
        "clients",
        "client",
        "meetings",
        "meeting",
        "reports",
        "report",
        "documents",
    },
    "Personal": {
        "personal",
        "family",
        "home",
        "private",
        "travel",
        "vacation",
        "photos",
        "photo",
        "memories",
    },
}


CONTENT_CATEGORIES = {
    "College": {
        "assignment",
        "exam",
        "semester",
        "lecture",
        "notes",
        "lab",
        "practical",
        "dbms",
        "java",
        "python",
        "operating system",
        "computer network",
        "data structure",
        "algorithm",
        "university",
        "college",
        "course",
        "subject",
    },
    "Work": {
        "invoice",
        "meeting",
        "client",
        "project",
        "report",
        "proposal",
        "presentation",
        "salary",
        "office",
        "business",
        "company",
        "employee",
        "deadline",
    },
    "Personal": {
        "personal",
        "family",
        "travel",
        "vacation",
        "passport",
        "insurance",
        "medical",
        "home",
        "private",
    },
}


CONTENT_EXTENSIONS = {
    ".txt",
    ".md",
    ".csv",
    ".rtf",
}